<?php

declare(strict_types=1);

namespace Automattic\DependabotDirectories\Write;

use Automattic\DependabotDirectories\Detection\Block;

/**
 * The pull request description: the problem, what was mapped, and where it
 * came from.
 */
final class PullRequestBody
{
    /**
     * A repository yielding more than this many entries produces a
     * description nobody reads.
     */
    private const MAX_LISTED = 25;

    /**
     * @param list<Block> $missing
     */
    public static function render(array $missing): string
    {
        $body = "Dependabot only updates a lockfile it has been pointed at. Where a lockfile is not at the default path — workspaces, monorepos, anything outside the repository root — security PRs ship without the lockfile update, CI stays red, and auto-merge never fires.\n\n";
        $body .= "This maps the directories that actually hold manifests and lockfiles.\n\n";
        $body .= "Detected:\n\n";

        foreach ($missing as $i => $block) {
            if (self::MAX_LISTED === $i) {
                $body .= sprintf("- ... and %d more\n", count($missing) - self::MAX_LISTED);
                break;
            }
            $body .= $block->isGlob
                ? sprintf("- `%s` -> `%s` (glob)\n", $block->ecosystem->value, $block->directory)
                : sprintf("- `%s` -> `%s`\n", $block->ecosystem->value, $block->directory);
        }

        $body .= "\nExisting entries were left untouched — this only appends.\n\n";
        $body .= "Generated by `dependabot-directories` ([QAO-641](https://linear.app/a8c/issue/QAO-641)).\n";

        return $body;
    }
}
