name: Lint

on:
    push:
        branches: [main]
        paths:
            - '.github/workflows/**'
    pull_request:
        paths:
            - '.github/workflows/**'

jobs:
    actionlint:
        name: actionlint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Download actionlint
              id: get_actionlint
              # actionlint v1.7.12
              run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/914e7df21a07ef503a81201c76d2b11c789d3fca/scripts/download-actionlint.bash)
              shell: bash
            - name: Check workflow files
              run: ${{ steps.get_actionlint.outputs.executable }} -color
              shell: bash
